name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  
jobs:
  # Job to set up the Python environment, install dependencies, and run tests
  test:
    runs-on: ubuntu-latest  # The environment for the job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checks out the repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify the Python version

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt  # Install dependencies from your requirements file

      - name: Set up Django Database
        run: |
          python manage.py migrate  # Set up database migrations for testing

      - name: Run tests
        run: |
          python manage.py test  # Run the Django tests
